# Generated by Django 4.0.5 on 2022-08-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option_a', models.CharField(max_length=15)),
                ('option_b', models.CharField(max_length=15)),
                ('option_c', models.CharField(max_length=15)),
                ('option_d', models.CharField(max_length=15)),
            ],
        ),
    ]
